development:
  adapter: sqlite
  encoding: unicode
  database: GitPub_d
  pool: 5
  
test:
  adapter: postgresql
  encoding: unicode
  database: GitPub_t
  pool: 5
  username: GitPub
  password: GitPubPass

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
